### ISSUE TITLE
control tags in pashmak

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashm-html#1]
Hi
Now we can not using html tags and control that ,
like this :
```html
<h1 class="test">Hello World</h1>
{
$h1 = html->select('.test')
$h1->content('Hello World With Pashmak')
}

**Comment by parsampsh** [comment]
This is not needed. This is javascript's work :)

**Comment by Paptoos** [comment]
and why using this framework ?

**Comment by parsampsh** [comment]
This library is only for **rendering pashmak code inside another formats(Like html)**. You haven't this feature in none of other backend techs. Backend not needs to handle html tags.

**Comment by parsampsh** [comment]
Also we don't need to RE-Write a javascript engine

**Comment by Paptoos** [comment]
It is a backend ?! if it is backend we do not need this library , it is frontend !!!

**Comment by parsampsh** [comment]
This is something like php interpreter:

```php
<div>
<?php
echo 'hello';
?>
</div>
```

```bash
<div>
{
println('hello world')
}
</div>
```

:)

**Comment by parsampsh** [comment]
> It is a backend ?! if it is backend we do not need this library , it is frontend !!!

Hey man! This is something like **Blade**, **Jinja**, **Razor**...(Read about them) This is ONLY FOR BACKEND and IS NOT RELATED TO HTML. this only renders the code inside another text formats!!(pashm-**html** name is ONLY a symbol). This engine reads the code, runs the pashmak codes between that and returns the response. then browser gets the response and renders the HTML. If you wanna do this, use Javascript and JQuery. None of backend technologies haven't Any thing to run something like javascript at server side to handle html tags. And no one is not stupid to RE-write Javascript to handle html tags at server. Also in other look point this is Impossible. Sure if this is possible, php, django, nodjes and... created it, but is not. Did you undrestand?

**Comment by parsampsh** [comment]
@Paptoos Amirmohammad, have you Twitter or Telegram? Can us connect?
